# -*- coding: utf-8 -*-
"""Customer_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZlujoYDw3kbBs1YO9gYkPhDjyFcG03tZ

# ***Customer Churn Analysis***

**Business Objective**

Analyze customer churn behavior and identify factors contributing to customer attrition using exploratory data analysis and machine learning models.

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset"""

df = pd.read_csv("customer_churn.csv")
df.head()

"""Dataset Overview"""

df.info()
df.describe(include='all')

"""Observations
Dataset contains customer demographic and service information.
Several categorical variables require encoding.
TotalCharges requires datatype conversion.

# **Data Cleaning & Preprocessing**

**Objective**

Prepare the dataset for analysis and machine learning by handling incorrect datatypes and missing values.
"""

df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

"""Observations

1.Converted TotalCharges column from object
datatype to numeric format.

2.Invalid values were converted into null values using errors='coerce'.

Handle Missing Values
"""

df.isnull().sum()

"""Remove Null Records"""

df.dropna(inplace=True)

df.reset_index(drop=True, inplace=True)

"""Observations
*   Removed rows containing missing values.
*   Reset index after cleaning the dataset.

Verify Cleaned Dataset
"""

df.info()

"""Observations

1.Dataset is now cleaned and ready for exploratory data analysis.

2.Numerical and categorical columns are properly structured.

# **Exploratory Data Analysis (EDA)**

Objective

Analyze customer behavior patterns and identify factors contributing to customer churn using visual analysis.

Churn Distribution
"""

sns.countplot(data=df, x='Churn')

plt.title("Customer Churn Distribution")

plt.xlabel("Churn")

plt.ylabel("Customer Count")

plt.show()

"""Insights
*   This visualization shows the distribution of churned and retained customers.
*   Helps understand overall churn imbalance in the dataset.

Contract Type vs Churn
"""

sns.countplot(
    data=df,
    x='Contract',
    hue='Churn'
)

plt.title("Contract Type vs Customer Churn")

plt.xlabel("Contract Type")

plt.ylabel("Customer Count")

plt.xticks(rotation=15)

plt.show()

"""Insights


*   Customers with month-to-month contracts are more likely to churn.
*   Long-term contracts show better customer retention.

Monthly Charges Distribution
"""

sns.histplot(
    data=df,
    x='MonthlyCharges',
    hue='Churn',
    kde=True,
    bins=30
)

plt.title("Monthly Charges Distribution by Churn")

plt.xlabel("Monthly Charges")

plt.ylabel("Frequency")

plt.show()

"""Insights


*  Customers with higher monthly charges show increased churn probability.
*   Pricing may influence customer retention behavior.

Tenure vs Monthly Charges
"""

sns.scatterplot(
    data=df,
    x='tenure',
    y='MonthlyCharges',
    hue='Churn'
)

plt.title("Tenure vs Monthly Charges")

plt.xlabel("Tenure")

plt.ylabel("Monthly Charges")

plt.show()

"""Insights


* Customers with lower tenure are more likely to churn.
*   Long-term customers generally show better retention patterns.

Correlation Heatmap
"""

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(numeric_only=True),
    cmap='coolwarm'
)

plt.title("Feature Correlation Heatmap")

plt.show()

"""Insights


*   Displays relationships between numerical variables.
*   Helps identify features strongly associated with churn.

# **Feature Engineering & Data Preprocessing**

Objective

Convert categorical variables into numerical format and prepare the dataset for machine learning model training.

Label Encoding
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

binary_cols = [
    'gender',
    'Partner',
    'Dependents',
    'PhoneService',
    'PaperlessBilling',
    'Churn'
]

for col in binary_cols:
    df[col] = le.fit_transform(df[col])

"""Insights


*   Binary categorical variables were converted into numerical format.
*   Machine learning models require numerical input data.

One-Hot Encoding
"""

df = pd.get_dummies(
    df,
    columns=[
        'InternetService',
        'MultipleLines',
        'OnlineSecurity',
        'OnlineBackup',
        'DeviceProtection',
        'TechSupport',
        'StreamingTV',
        'StreamingMovies',
        'Contract',
        'PaymentMethod'
    ],
    drop_first=True
)

"""Insights


*   One-Hot Encoding converts multi-category columns into numerical dummy variables.
*   drop_first=True helps avoid multicollinearity.

Verify Transformed Dataset
"""

df.head()

"""Dataset Information After Encoding"""

df.info()

"""Insights


*   All categorical variables are now converted into machine-learning-compatible numerical format.
*   Dataset is now ready for feature selection and model training.

Define Features & Target Variable
"""

X = df.drop(['Churn', 'customerID'], axis=1)

y = df['Churn']

"""Insights


*   X contains input features used for prediction.
*   y contains the target variable (Churn).

Train-Test Split
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Insights


*   Training data is used for model learning.
*   Testing data is used for evaluating model performance.
*   80-20 split helps maintain balanced evaluation.

# **Model Building — Logistic Regression**

**Objective**

Train a Logistic Regression model to predict customer churn and evaluate its performance using classification metrics.

Import Logistic Regression
"""

from sklearn.linear_model import LogisticRegression

"""Train Logistic Regression Model"""

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

"""Insights


*   Logistic Regression is a supervised machine learning algorithm used for binary classification.
*   The model learns patterns associated with customer churn behavior.

Generate Predictions
"""

y_pred = log_model.predict(X_test)

"""Insights


*   Predictions are generated using unseen test data
*   Output values:

      0 → Customer Retained
      
      1 → Customer Churned

Model Accuracy
"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Logistic Regression Accuracy:", accuracy)

"""Insights


*   Accuracy measures the percentage of correctly predicted records.
*   Higher accuracy indicates better prediction performance.

Confusion Matrix
"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

"""Insights


*   Confusion Matrix evaluates:

       Correct Predictions

       Incorrect Predictions

       False Positives
    
       False Negatives

Classification Report
"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""Insights


*   Precision → Prediction accuracy for positive class

*   Recall → Ability to identify actual churn cases

* F1-Score → Balance between Precision and Recall

Confusion Matrix Visualization
"""

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_estimator(
    log_model,
    X_test,
    y_test
)

plt.title("Confusion Matrix - Logistic Regression")

plt.show()

"""Insights


*   Visual representation of prediction performance.
*   Helps understand model classification quality more clearly.

# **Model Building — Random Forest Classifier**

Objective

Train a Random Forest model to improve churn prediction performance using ensemble learning techniques.

Import Random Forest Classifier
"""

from sklearn.ensemble import RandomForestClassifier

"""Train Random Forest Model"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

"""Insights


*   Random Forest combines multiple decision trees for prediction.
*  Ensemble learning helps improve model accuracy and reduce overfitting.

Generate Predictions
"""

rf_pred = rf_model.predict(X_test)

"""Insights


*   Predictions are generated using test data.
*   Used to evaluate model performance on unseen records.

Random Forest Accuracy
"""

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

"""Insights


*   Accuracy measures overall prediction correctness.
*   Random Forest generally performs better on complex datasets.

Random Forest Confusion Matrix
"""

rf_cm = confusion_matrix(y_test, rf_pred)

print(rf_cm)

"""Insights

*   Helps evaluate:

    correctly classified customers

    false churn predictions
    
    missed churn cases

Random Forest Classification Report
"""

print(classification_report(y_test, rf_pred))

"""Insights


*   Evaluates model performance using:


     *   Precision
     *   Recall

     *   F1-Score


*   Useful for understanding churn prediction quality.

Confusion Matrix Visualization
"""

ConfusionMatrixDisplay.from_estimator(
    rf_model,
    X_test,
    y_test
)

plt.title("Confusion Matrix - Random Forest")

plt.show()

"""Insights


*   Provides a visual understanding of prediction performance.
*   Helps compare model effectiveness against Logistic Regression.

Feature Importance Analysis
"""

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

feature_importance.head(10)

"""Insights


*   Identifies the most influential features affecting customer churn.
*   Helps businesses focus on key churn-driving factors.

Visualize Top Features
"""

plt.figure(figsize=(10,6))

sns.barplot(
    data=feature_importance.head(10),
    x='Importance',
    y='Feature'
)

plt.title("Top 10 Important Features")

plt.xlabel("Importance Score")

plt.ylabel("Features")

plt.show()

"""Insights


*   Visualizes the top factors contributing to customer churn.
*   Useful for business decision-making and retention strategy planning.

# **Final Business Insights & Recommendations**

Key Findings:
- Customers with month-to-month contracts showed higher churn probability.
- Higher monthly charges were associated with increased churn risk.
- Customers with shorter tenure were more likely to leave the service.
- Contract type and payment methods significantly influenced customer retention.

Business Recommendations:
- Introduce discounts for long-term subscription plans.
- Create loyalty programs for new customers.
- Target high-risk customers using retention campaigns.
- Improve customer engagement strategies for short-tenure users.

Conclusion:
The project successfully analyzed customer churn behavior using exploratory data analysis and machine learning models. Random Forest demonstrated stronger predictive capability and identified critical churn-driving factors that can support customer retention strategies.
"""